M48
; DRILL file {KiCad 6.0.7-f9a2dced07~116~ubuntu20.04.1} date mié 10 ago 2022 10:50:10
; FORMAT={-:-/ absolute / inch / decimal}
; #@! TF.CreationDate,2022-08-10T10:50:10-04:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,6.0.7-f9a2dced07~116~ubuntu20.04.1
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
INCH
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.1260
%
G90
G05
T1
X5.7301Y-3.8007
X8.3876Y-3.8007
T0
M30
