M48
; DRILL file {KiCad 6.0.8-f2edbf62ab~116~ubuntu20.04.1} date jue 03 nov 2022 13:34:05
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2022-11-03T13:34:05-03:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,6.0.8-f2edbf62ab~116~ubuntu20.04.1
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C3.200
%
G90
G05
T1
X145.544Y-85.568
X163.83Y-74.93
T0
M30
