M48
; DRILL file {KiCad 6.0.7-f9a2dced07~116~ubuntu20.04.1} date vie 29 jul 2022 11:58:21
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2022-07-29T11:58:21-04:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,6.0.7-f9a2dced07~116~ubuntu20.04.1
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C3.200
%
G90
G05
T1
X145.599Y-86.25
X213.099Y-86.25
T0
M30
